name: swahili_nfc
description: A comprehensive Flutter package for NFC business card applications with a focus on secure contact exchange.
version: 0.1.0
homepage: https://github.com/swahiliconnect/swahili_nfc
repository: https://github.com/swahiliconnect/swahili_nfc
issue_tracker: https://github.com/swahiliconnect/swahili_nfc/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.2
  encrypt: ^5.0.1
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.swahilicard.nfc
        pluginClass: SwahiliNFCPlugin
      ios:
        pluginClass: SwahiliNFCPlugin